### ISSUE TITLE
Can't require ember-list-view.js or ember-widgets.js

### ISSUE THREAD

**Issue by Kuzirashi** [DockYard/ember-validations#227]
When I try to require ember-list-view.js or ember-widgets.js in my Brocfile.js I get an error:
~~~~
Error while processing route: training.index Could not find module ember-validations Error: Could not find module ember-validations
    at requireModule (http://localhost:4200/assets/vendor.js:65:13)
    at reify (http://localhost:4200/assets/vendor.js:48:30)
    at requireModule (http://localhost:4200/assets/vendor.js:76:17)
    at resolveOther (http://localhost:4200/assets/vendor.js:64111:20)
    at apply (http://localhost:4200/assets/vendor.js:33208:27)
    at superWrapper (http://localhost:4200/assets/vendor.js:32780:15)
    at __exports__.default.EmberObject.extend.resolve (http://localhost:4200/assets/vendor.js:17186:27)
    at Object.resolve [as resolver] (http://localhost:4200/assets/vendor.js:16984:25)
    at resolve (http://localhost:4200/assets/vendor.js:15277:32)
    at Object.Container.resolve (http://localhost:4200/assets/vendor.js:14848:16)
~~~~
Brocfile.js:
~~~~
/* global require, module */

var EmberApp = require('ember-cli/lib/broccoli/ember-app');
var pickFiles = require('broccoli-static-compiler');

var app = new EmberApp({
  fingerprint: {
    enabled: false
  }
});
app.import('bower_components/ember-data/ember-data.js.map', { destDir: 'assets' }); 

app.import('bower_components/ember-forms/dist/globals/main.js');

var bootstrapFonts = pickFiles('bower_components/bootstrap-sass-official/assets/fonts/bootstrap', {
  srcDir: '/',
  destDir: '/fonts/bootstrap'
});

app.import('bower_components/bootstrap-sass-official/assets/javascripts/bootstrap/modal.js');

var fontAwesomeFonts = pickFiles('bower_components/font-awesome/fonts', {
  srcDir: '/',
  destDir: '/fonts'
});

app.import('bower_components/jquery-cookie/jquery.cookie.js');
app.import('bower_components/ember-droplet/dist/ember-droplet.min.js');

app.import('bower_components/timeago/jquery.timeago.js')
app.import('bower_components/timeago/locales/jquery.timeago.pl.js')

app.import('bower_components/jquery-autosize/jquery.autosize.min.js')

app.import('bower_components/maphilight/jquery.maphilight.min.js')

app.import('bower_components/fancybox/source/jquery.fancybox.css');
app.import('bower_components/fancybox/source/jquery.fancybox.pack.js')

var fancyFiles = pickFiles('bower_components/fancybox', {
    srcDir: '/source',
    files: ['**/*.png', '**/*.gif'],
    destDir: '/assets'
});

app.import('bower_components/jquery-ui/ui/core.js');
app.import('bower_components/jquery-ui/ui/widget.js');
app.import('bower_components/jquery-ui/ui/mouse.js');
app.import('bower_components/jquery-ui/ui/draggable.js');
app.import('bower_components/jquery-ui/ui/droppable.js');
app.import('bower_components/jquery-ui/ui/sortable.js');

app.import('vendor/microfiche.js');

app.import('bower_components/lodash/dist/lodash.js');
app.import('bower_components/ember-list-view/list-view.js');
// ember-widgets
app.import('bower_components/ember-widgets/dist/js/ember-widgets.js');
app.import('bower_components/ember-widgets/dist/css/ember-widgets.css');
var widgetsImages = pickFiles('bower_components/ember-widgets/dist', {
    srcDir: '/img',
    destDir: '/assets'
});

var index = app.legacyFilesToAppend.indexOf('bower_components/handlebars/handlebars.runtime.js');
if(index) {
  app.legacyFilesToAppend[index] = 'bower_components/handlebars/handlebars.js';
}

// Use `app.import` to add additional libraries to the generated
// output files.
//
// If you need to use different assets in different
// environments, specify an object as the first parameter. That
// object's keys should be the environment name and the values
// should be the asset to use in that environment.
//
// If the library that you are including contains AMD or ES6
// modules that you would like to import into your application
// please specify an object with the list of modules as keys
// along with the exports of each module as its value.

module.exports = app.toTree([bootstrapFonts, fontAwesomeFonts, fancyFiles, widgetsImages]);
~~~~

**Comment by martndemus** [comment]
I am going to close this issue for now, feel free to reopen this issue if you feel like it's still relevant and we should take a look at it.
