### ISSUE TITLE
error w/ ember-cli

### ISSUE THREAD

**Issue by joshpfosi** [dockyard/ember-validations#228]
I've been experiencing this issue on a basic unit test while I'm transition to Ember-CLI

    TypeError: Cannot read property 'forEach' of undefined
    at Object.forEach (http://localhost:4200/assets/vendor.js:27244:17)
    at __exports__.default.Ember.Mixin.create.buildRuleValidator (http://localhost:4200/assets/vendor.js:76983:35)
    at __exports__.default.Ember.Mixin.create.buildValidators (http://localhost:4200/assets/vendor.js:76949:18)
    at __exports__.default.Ember.Mixin.create.init (http://localhost:4200/assets/vendor.js:76931:14)
    at apply (http://localhost:4200/assets/vendor.js:32883:32)
    at superWrapper [as init] (http://localhost:4200/assets/vendor.js:32457:15)
    at apply (http://localhost:4200/assets/vendor.js:32883:32)
    at new Class (http://localhost:4200/assets/vendor.js:47483:9)
    at Function.Mixin.create.create (http://localhost:4200/assets/vendor.js:47941:16)
    at Ember.Object.extend.buildRecord (http://localhost:4200/assets/vendor.js:75309:27)

This is my `bower.json`:

    {
    "name": "jobs-tuftsdaily",
    "dependencies": {
    "handlebars": "~1.3.0",
    "jquery": "^1.11.1",
    "ember": "1.8.1",
    "ember-data": "1.0.0-beta.12",
    "ember-resolver": "~0.1.11",
    "loader.js": "ember-cli/loader.js#1.0.1",
    "ember-cli-shims": "ember-cli/ember-cli-shims#0.0.3",
    "ember-cli-test-loader": "rwjblue/ember-cli-test-loader#0.0.4",
    "ember-load-initializers": "ember-cli/ember-load-initializers#0.0.2",
    "ember-qunit": "0.1.8",
    "ember-qunit-notifications": "0.0.4",
    "qunit": "~1.15.0",
    "bootstrap": "~3.3.1"
      }
    }

This is the failing test:

    test('it exists', function() {
      var model = this.subject();
      // var store = this.store();
      ok(!!model);
    });

**Comment by bcardarella** [comment]
This is typically the result of updating from an older version of ember-cli. Can you try:

`rm -rf node_modules && npm cache clear && npm install`

**Comment by joshpfosi** [comment]
Yes, I think that was it as this error has since gone away. Thanks!
