### ISSUE TITLE
 Cannot call get with 'cache' on an undefined object error in the model unit test

### ISSUE THREAD

**Issue by lessless** [DockYard/ember-validations#255]
Hello Team,
maybe I missed something out, as there is no any kind user reports for that, but still, here is the case:
any kind of validation inside model cause model's unit test to fail with 2.0.0-alpha.2 and ember-cli 0.1.15.

```javascript
// model 
import DS from 'ember-data';
import EmberValidations from 'ember-validations';

export default DS.Model.extend(EmberValidations.Mixin, {
   validations: {
    name: {
      presence: true
    }
  },

  name: DS.attr('string'),
});

});

// model unit test
import {
  moduleForModel,
  test
} from 'ember-qunit';

moduleForModel('user', 'User', {
  // Specify the other units that are required for this test.
  needs: []
});

test('it exists', function(assert) {
  var model = this.subject();
  // var store = this.store();
  assert.ok(!!model);
});

```

here is the backtrace from the browser 

```javascript

Died on test #1     at Object.test (http://localhost:4200/assets/test-support.js:1693:11)
    at http://localhost:4200/assets/ktd.js:1466:15
    at requireModule (http://localhost:4200/assets/vendor.js:79:29)
    at Object.TestLoader.require (http://localhost:4200/assets/test-loader.js:29:9)
    at Object.TestLoader.loadModules (http://localhost:4200/assets/test-loader.js:21:18)
    at Function.TestLoader.load (http://localhost:4200/assets/test-loader.js:36:24)
    at http://localhost:4200/assets/test-support.js:5294:16: Assertion Failed: Cannot call get with 'cache' on an undefined object.@ 11 ms
Source: 	
Error: Assertion Failed: Cannot call get with 'cache' on an undefined object.
    at new Error (native)
    at Error.EmberError (http://localhost:4200/assets/vendor.js:25990:23)
    at Object.Ember.assert (http://localhost:4200/assets/vendor.js:17487:15)
    at get (http://localhost:4200/assets/vendor.js:29852:13)
    at lookupValidator (http://localhost:4200/assets/vendor.js:81344:17)
    at exports.default.Ember.default.Mixin.create.buildRuleValidator (http://localhost:4200/assets/vendor.js:81448:68)
    at exports.default.Ember.default.Mixin.create.buildValidators (http://localhost:4200/assets/vendor.js:81414:16)
    at exports.default.Ember.default.Mixin.create.init (http://localhost:4200/assets/vendor.js:81396:12)
    at superWrapper [as init] (http://localhost:4200/assets/vendor.js:31732:22)
    at new Class (http://localhost:4200/assets/vendor.js:47182:16)

```
and from the phantomjs
```javascript
not ok 20 PhantomJS 1.9 - User: it exists
    ---
        actual: >
            null
        message: >
            Died on test #1     at http://localhost:7357/assets/test-support.js:2535
                at test (http://localhost:7357/assets/test-support.js:1693)
                at http://localhost:7357/assets/ktd.js:1470
                at http://localhost:7357/assets/vendor.js:79
                at http://localhost:7357/assets/test-loader.js:29
                at http://localhost:7357/assets/test-loader.js:21
                at http://localhost:7357/assets/test-loader.js:36
                at http://localhost:7357/assets/test-support.js:5294: Assertion Failed: Cannot call get with 'cache' on an undefined object.
        Log: >

```
if I comment out presence validation in the model than tests pass

**Comment by michaelBenin** [comment]
Also having this issue.

**Comment by wwwdata** [comment]
any news on this issue? I got this too

**Comment by misteroneill** [comment]
I encountered this issue as well. You need to add `'service:validations'` to the `needs` for your test.

This appears to have been recently added to the [README](https://github.com/dockyard/ember-validations#with-ember-qunit).

**Comment by wwwdata** [comment]
ah, thx!

**Comment by martndemus** [comment]
I am going to close this issue for now, feel free to reopen this issue if you feel like it's still relevant and we should take a look at it.
