### ISSUE TITLE
Strange Ember.I18n.pluralForm requires a language when enabling a minimum length for a parameter

### ISSUE THREAD

**Issue by mansona** [DockYard/ember-validations#273]
So this code: 
```
        password: {
            confirmation: true,
            length: {
                minimum: 8
            }
        },
```
generates this error: 
```
Error while processing route: signup Ember.I18n.pluralForm requires a language Error: Ember.I18n.pluralForm requires a language
    at Object.pluralForm (http://localhost:5000/assets/vendor.js:77614:35)
    at Object.Ember.Evented.apply.template (http://localhost:5000/assets/vendor.js:77319:23)
    at Object.Ember.Evented.apply.t (http://localhost:5000/assets/vendor.js:77329:23)
    at Object.exports.default.render (http://localhost:5000/assets/vendor.js:77767:38)
    at exports.default.Base.default.extend.renderMessageFor (http://localhost:5000/assets/vendor.js:78359:79)
    at exports.default.Base.default.extend.renderBlankMessage (http://localhost:5000/assets/vendor.js:78365:21)
    at exports.default.Base.default.extend.call (http://localhost:5000/assets/vendor.js:78373:39)
    at null._validate (http://localhost:5000/assets/vendor.js:78040:14)
    at sendEvent (http://localhost:5000/assets/vendor.js:23345:27)
    at new Class (http://localhost:5000/assets/vendor.js:44199:9)
```
Current Versions: 
```
Ember      : 1.10.0
Ember Data : 1.0.0-beta.16
jQuery     : 1.11.2
ember-validations        : 2.0.0-alpha.3
```
This only shows up when i add this portion to the validation: 
```
 length: {
                minimum: 8
            }
```
Any thoughts?

**Comment by Alimero** [comment]
Is there any solution? I got the same error when trying to use ember-i18n and ember-validations.

**Comment by mortenbo** [comment]
This is not the fault of `ember-validations`. As the `ember-i18n` docs states:

```
If you want to support inflection based on count, you will also need to include Ember-I18n's pluralization support (lib/i18n-plurals.js) after the Ember-I18n core (lib/i18n.js) itself and set Ember.I18n.locale to the current locale code (e.g. "de").
```

By setting the locale it goes away:

```javascript
Ember.I18n.locale = 'en';
```

**Comment by martndemus** [comment]
I am going to close this issue for now, feel free to reopen this issue if you feel like it's still relevant and we should take a look at it.
