### ISSUE TITLE
Ember Validations mixin no longer working on model with ember data beta.19

### ISSUE THREAD

**Issue by jcope2013** [dockyard/ember-validations#313]
this.model.get(this.property) in the call function of the local validators is throwing 

```
Error while processing route: index Cannot read property '_attributes' of undefined TypeError: Cannot read property '_attributes' of undefined
    at ember$data$lib$system$model$attributes$$hasValue (http://builds.emberjs.com/beta/ember-data.js:9470:27)
    at ember$data$lib$utils$computed$polyfill$$default.get (http://builds.emberjs.com/beta/ember-data.js:9550:15)
    at func (http://builds.emberjs.com/beta/ember-data.js:9261:31)
    at Descriptor.ComputedPropertyPrototype.get (http://builds.emberjs.com/tags/v1.11.3/ember.debug.js:10404:26)
    at Object.get (http://builds.emberjs.com/tags/v1.11.3/ember.debug.js:15664:19)
    at exports.default.mixin.Mixin.create.get (http://builds.emberjs.com/tags/v1.11.3/ember.debug.js:30404:27)
    at Ember.Validations.validators.local.Presence.Ember.Validations.validators.Base.extend.call (http://builds.dockyard.com.s3.amazonaws.com/ember-validations/ember-validations-latest.js:671:34)
    at null._validate (http://builds.dockyard.com.s3.amazonaws.com/ember-validations/ember-validations-latest.js:245:12)
    at Object.sendEvent (http://builds.emberjs.com/tags/v1.11.3/ember.debug.js:12428:25)
    at new Class (http://builds.emberjs.com/tags/v1.11.3/ember.debug.js:31899:14)
```

non working version - Ember Data beta.19 - http://emberjs.jsbin.com/karomoduqe/1/edit
working version - Ember Data beta.18 - http://emberjs.jsbin.com/tonazedabe/1/edit

**Comment by GeoffreyBooth** [comment]
+1

**Comment by jcope2013** [comment]
seems like a fix landed on canary today (http://emberjs.jsbin.com/satagecovi/1/edit)

https://github.com/emberjs/data/pull/3262
