### ISSUE TITLE
Qunit dies when executing controller.validate();

### ISSUE THREAD

**Issue by khanhhua** [DockYard/ember-validations#395]
Basically I added the EmberValidations mixin to my controller class. When I run qunit, it dies. Running normally in a browser is OK. I am using Ember Validation 2.0.alpha-4.

```
test('it can handle error for missing required fields', function (assert) {
  let controller = this.subject(mock);

  Ember.run(function () {
    controller.validate();
  });

  assert.ok(true);
});
```

```
Died on test #1     at test (http://localhost:4200/assets/test-support.js:1644:11)
    at http://localhost:4200/assets/tests.js:2492:24
    at mod.state (http://localhost:4200/assets/vendor.js:160:29)
    at tryFinally (http://localhost:4200/assets/vendor.js:40:14)
    at requireModule (http://localhost:4200/assets/vendor.js:158:5)
    at Object.TestLoader.require (http://localhost:4200/assets/test-loader.js:29:9)
    at Object.TestLoader.loadModules (http://localhost:4200/assets/test-loader.js:21:18): <(unknown mixin):ember300>
```

**Comment by martndemus** [comment]
I am going to close this issue for now, feel free to reopen this issue if you feel like it's still relevant and we should take a look at it.
