### ISSUE TITLE
I can't run this project to contribute

### ISSUE THREAD

**Issue by villander** [DockYard/ember-validations#415]
after run `ember s`: 

```
Livereload server on port 35729
Serving on http://localhost:4200/
ENOENT: no such file or directory, scandir 'node_modules/ember-cli-ic-ajax/node_modules/'
Error: ENOENT: no such file or directory, scandir 'node_modules/ember-cli-ic-ajax/node_modules/'
    at Error (native)
    at Object.fs.readdirSync (fs.js:813:18)
    at /Users/flama/Projects/ember-validations/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:32:21
    at Array.map (native)
    at mergeRelativePath (/Users/flama/Projects/ember-validations/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:30:29)
    at /Users/flama/Projects/ember-validations/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:23:5
    at lib$rsvp$$internal$$tryCatch (/Users/flama/Projects/ember-validations/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/flama/Projects/ember-validations/node_modules/rsvp/dist/rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (/Users/flama/Projects/ember-validations/node_modules/rsvp/dist/rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (/Users/flama/Projects/ember-validations/node_modules/rsvp/dist/rsvp.js:1198:9)
````

**Comment by villander** [comment]
My environment:
````
ember-cli: 2.5.0
node: 4.0.0
os: darwin x64
npm: 3.8.6
```

**Comment by martndemus** [comment]
I am going to close this issue for now, feel free to reopen this issue if you feel like it's still relevant and we should take a look at it.
